# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cacc92ec7098ba999167d9f92efdce7320f8612ae6312afd7f3a0f69c5fd44e694349a51b7ef784b039acd46924a0ff89f61fc7397020b0bdb5f7078f78aab7b

  # google custom search
  google_api_key : 'AIzaSyA3EpugqUq-A-RShiIcfn5UyJU_R3lMKos'
  google_custom_search_id : '008250860226409482484:fvpilalvu4w'

  #pixabay API KEY
  pixabay_api_key : '4667129-669047c35c5e5c409e4df6345'


test:
  secret_key_base: ec7ce9a3334eef891cf77acb9bc4d80b82b0c43658e69e09a71156114abf93dce239170d89d02a891bdda9531a8c7630c6b77a607d31cccb64ed827f4c0a64b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
